### ISSUE TITLE
Commit log mentions submodules for starch but it's actually directly in the repo

### ISSUE THREAD

**Issue by gtjoseph** [flightaware/dump1090#102]
Is it supposed to be a submodule and accidentally got checked in or are you going to leave it as checked in code?  I do see there's a starch repo now.

**Comment by gtjoseph** [comment]
Nevermind.  I just saw the following comment further down in the commit...
* Remove submodules in preparation for importing them directly

**Comment by mutability** [comment]
Yeah, submodules are sufficiently finicky that I figured it was easier to just inline the code directly; merging updates by hand when needed is not a big deal.
