### ISSUE TITLE
skyaware new WebUI issue

### ISSUE THREAD

**Issue by DenyDarko** [flightaware/dump1090#121]
Hey there,
The button shown on the screenshot does nothing. It's clickable and everything but it doesn't perform any action:

![1sk](https://user-images.githubusercontent.com/3320229/111456304-82047c00-871f-11eb-97d5-01246d570058.png)

Is that expected?

**Comment by eric1tran** [comment]
That button should only show up for SD card installs since it includes piaware-web and exposes status.json which contains a link to your stats page. Are you seeing it on yours? Do you have piaware-web installed by chance?

**Comment by DenyDarko** [comment]
> That button should only show up for SD card installs since it includes piaware-web and exposes status.json which contains a link to your stats page. Are you seeing it on yours? Do you have piaware-web installed by chance?

Nope:

`root@raspberrypi:~ # apt list --installed pia*
Listing... Done
piaware/now 5.0 arm64 [installed,local]
root@raspberrypi:~ #
`
