### ISSUE TITLE
No map display at localhost:8080

### ISSUE THREAD

**Issue by paulburton0** [flightaware/dump1090#133]
Using Ubuntu 21.04, I cloned the repo and did 'make' with no errors. I can start dump1090 with --interactive and see good data in the terminal. However, when I use the --net option, I go to localhost:8080 and I get "Unable to Connect" in the browser. What am I missing?

**Comment by mutability** [comment]
dump1090 does not provide an internal webserver. Use `--write-json` to write the dynamic files somewhere (ideally on tmpfs) and use a separate webserver to serve them and the static files. See the debian package for a sample lighttpd config that does this.
