### ISSUE TITLE
Range Rings and Altitude Chart legend almost impossible to see when you select ESRI Satellite as your overlay

### ISSUE THREAD

**Issue by cotero2002** [flightaware/dump1090#136]
The range rings and altitude chart legend color are black with no other color option.  If you select ESRI Satellite as your map overlay, the dark nature of the view make the rings and numbers almost impossible to see.  In contrast with the "aircraft labels" which are presented in white color making a very nice contrast with the dark background.  
![Screenshot_2](https://user-images.githubusercontent.com/25139994/124304904-5b354e80-db32-11eb-89fc-925bd3707bc3.jpg)

Showing the range rings and altitude chart legend in another color (white for example) will be great for those using the ESRI Satellite overlay.

**Comment by eric1tran** [comment]
Improved visibility for version 8.0
