### ISSUE TITLE
Location of a web interface

### ISSUE THREAD

**Issue by MatejKovacic** [flightaware/dump1090#157]
I am really sorry, but I am unable to find the location of web interface. I am running dump1090-fa locally on a Ubuntu 20.04 laptop with RTL-SDR device (RTL2832U).

I start the app with `dump1090-fa --interactive --ppm 34`, but on a `http://localhost/dump1090` is nothing.

Also, it would be nice if webserver and URL info would be printed out in console or at least in help...

**Comment by mutability** [comment]
The web interface is served externally to dump1090-fa.

If you built a package and installed that, the package includes configuration for lighttpd to serve the web interface on port 8080 or at `/skyaware/` or at `/dump1090-fa/`

If you didn't build a package, it's up to you to arrange for the json output (written by `--write-json`) to be served somewhere along with the static files from `public_html`
