### ISSUE TITLE
Web page not showing

### ISSUE THREAD

**Issue by blogdemoi** [flightaware/dump1090#165]
Hello,

I installed the AUR package on my Manjaro https://aur.archlinux.org/packages/dump1090-fa-git then cd into usr/bin and ran `./dump1090 --interactive --net` then tried to open http://localhost:8080/ but nothing showing on the page 

> Firefox can’t establish a connection to the server at localhost:8080

In my terminal I have : 

![screenshot_2021-11-14-03:44:37](https://user-images.githubusercontent.com/83965802/141665577-7c22ff22-e947-4bd0-b2fe-2449b6ffe348.png)

I also did: 

```
systemctl start dump1090-fa
Failed to start dump1090-fa.service: Unit dump1090-fa.service not found.
```

What can be wrong?

Thank you.

**Comment by mutability** [comment]
dump1090 does not provide a webserver, you need to arrange for a separate webserver to serve the json & static files.

The Debian package does this automatically. I don't know anything about the aur package, you should contact the maintainer of that package.
