### ISSUE TITLE
Country flag of Switzerland is squeezed

### ISSUE THREAD

**Issue by by** [flightaware/dump1090#175]
The original country flag from https://dynamospanish.com/flags/countries/switzerland/ is square (as it should be); at https://github.com/flightaware/dump1090/blob/master/public_html/flags-tiny/Switzerland.png and https://github.com/flightaware/dump1090/blob/master/public_html_merged/flags-tiny/Switzerland.png, it is stretched to the rectangular format of the other flags

**Comment by mutability** [comment]
The original is actually not square (see the topmost "tiny" flag, which is what we use):

![Screenshot from 2022-03-07 14-09-47](https://user-images.githubusercontent.com/3055062/156977801-59624d1e-81ba-4699-b8b1-34788cc3ac92.png)

If you have a better version with the correct aspect ratio (it would need to still be a rectangular image of the same size, with transparency at the left/right edges), could you provide the new image or a PR updating it?

**Comment by by** [comment]
Yes, the original is incorrect; what about this one:
![Switzerland_square](https://user-images.githubusercontent.com/335425/156986025-c69021e0-3d39-4361-9da1-b72d86bc83f1.png)
