### ISSUE TITLE
NO INTERFACE WEBUI

### ISSUE THREAD

**Issue by vincenzogianfelice** [flightaware/dump1090#177]
Hi. How can I see the data through the WebUI (like the old dump1090)?

**Comment by mutability** [comment]
Arrange to serve the static & dynamic content from a separate webserver. There is no internal webserver.

The Debian package configured lighttpd to do this for you; either use the Debian package, or you can use those config files as a starting point for your own configuration.

**Comment by vincenzogianfelice** [comment]
thanks
