### ISSUE TITLE
dropped_samples counting is broken

### ISSUE THREAD

**Issue by wiedehopf** [flightaware/dump1090#178]
https://github.com/flightaware/dump1090/blob/849a3b73299b4f56620ab16a6b62d88e17f35608/dump1090.c#L897
https://github.com/flightaware/dump1090/blob/849a3b73299b4f56620ab16a6b62d88e17f35608/sdr_rtlsdr.c#L335

This fix for readsb-protobuf also applies to dump1090-fa:
https://github.com/Mictronics/readsb-protobuf/pull/21

actually two issues:
- outbuf->dropped is not reset and in dump1090.c dropped is used regardless of the magbuf discontinuous flag
- static variable dropped is never reset in sdr_rtl.c

**Comment by mutability** [comment]
Thanks for the fixes. I might move the initialization of `outbuf->dropped` into the fifo code so it's always done

**Comment by mutability** [comment]
nb: static variable seems to be correctly reset already

**Comment by wiedehopf** [comment]
yeah seems this wasn't correctly patched when Mictronics used your fifo code.
(i don't have any of the fifo code in my fork, still have the old dump1090 code for managing the buffers)

**Comment by wiedehopf** [comment]
Pretty sure the other part of the patch was still necessary.
The static dropped would have been reset and outbuf->dropped would have been added each time the buffer was being reused.

**Comment by mutability** [comment]
which "other part" do you mean? The change in the linked PR resets the per-buffer `dropped` on each acquire. I don't think there's anything else?

**Comment by wiedehopf** [comment]
Yeah you fixed that by setting outbuf-dropped to zero in fifo_acquire.
Sorry if the comment was ambiguous.
I meant you already did the part of the fix necessary for dump1090-fa
