### ISSUE TITLE
Fix host vs build var naming. Use DEB_HOST_ARCH in package builds breaks build on RaspiOS 64-bit (bullseye)

### ISSUE THREAD

**Issue by by** [flightaware/dump1090#212]
The latest commit on the dev tree breaks build on my Raspberry Pi4 with 64-bit bullseye, see here: [https://github.com/flightaware/dump1090/commit/a13cdc9830b4be31e63e9ef07459b241beedbeb5#commitcomment-94417626](url)

**Comment by mutability** [comment]
Can you try https://github.com/flightaware/dump1090/commit/542bfcafe23ee2959bc7caa5d105365b92156695 just commited to dev to see if that helps? (untested)

**Comment by by** [comment]
Yes, https://github.com/flightaware/dump1090/commit/542bfcafe23ee2959bc7caa5d105365b92156695 does it, thanks!
