### ISSUE TITLE
Adaptive Duty Cycle does not work as expected

### ISSUE THREAD

**Issue by by** [flightaware/dump1090#227]
I'm running the current version 9.0~dev from github on a Raspberry Pi with bookworm 64-bit.

Experimentally, I've tried to set `ADAPTIVE_DUTY_CYCLE=100` in `/etc/default/dump1090-fa` but `systemctl status dump1090-fa` only reports `adaptive: using 50% duty cycle`

**Comment by mutability** [comment]
> `ADAPTIVE_DUTY_CYCLE=100`

There is no such config setting (see `start-dump1090-fa` for the settings it knows about).

If you want to tune this you'll need to put `--adaptive-duty-cycle` in `EXTRA_OPTIONS`

**Comment by by** [comment]
Thank you!
