### ISSUE TITLE
--ifile not work

### ISSUE THREAD

**Issue by Sunxingzhezhexingsun** [flightaware/dump1090#248]
I am using dump1090-fa for signal file parsing, and the sample file is testfiles/modes1.bin of the original dump1090 project. When the original dump1090 is used, information about the parsed ADS-B packet can be displayed. However, when dump1090-fa is used, no information is displayed.
The following are the results of my experiments using dump1090-fa, dump1090, and dump1090-mutability respectively
<img width="1199" alt="image" src="https://github.com/user-attachments/assets/67299e36-c748-4209-8195-af4d46c3b8d0">

**Comment by mutability** [comment]
IIRC that sample file is very old and dates back to the original
demodulator which ran at 2MHz. The current demodulator expects 2.4MHz
input, so the old file won't work with it. I should probably remove it to
reduce confusion.
