### ISSUE TITLE
New flags not stackable?

### ISSUE THREAD

**Issue by shbisson** [flightaware/dump1090#83]
So I have been experimenting with the new dump 1090 flags, and I don't seem to be able to stack them. I would like to be able to use the URL http://192.0.0.1/dump1090-fa/?banner=hide?aircraftTrails=show in the configuration for my twitterbot, but it doesn’t  work (and also seems to crash chromedriver in selenium). Anyone able to get this to work?

**Comment by shbisson** [comment]
Thanks for the fix!

**Comment by shbisson** [comment]
Ah, a comment on the FA forums notes that the documentation has an error, and stacking is & not ? which I should have noticed having been doing this web thing since the early 90s!

**Comment by mutability** [comment]
Yep, it should just be the usual URL query parameter syntax with `&` separators
