### ISSUE TITLE
Default map

### ISSUE THREAD

**Issue by bensofficial** [flightaware/dump1090#98]
Hi,
I know that you can change the map or enable weather radar in the SkyAware map. But is there a possibility that the weather radar is enabled on default when you open this page. 
Thank you.

**Comment by mutability** [comment]
The layer settings are persisted to localStorage, is this not working for you?

**Comment by eric1tran** [comment]
@bensofficial The maps and weather settings are persistent at obj mentioned. Going to close this. If you are still having problems, you can open up another issue with repro steps.
